const $=s=>document.querySelector(s), canvas=$('#game'),ctx=canvas.getContext('2d'),beniPhoto=new Image();beniPhoto.src='beni.png';
let data=JSON.parse(localStorage.getItem('beniBigDay')||'null')||{coins:20,hunger:72,clean:70,happy:76,owned:[]};
data.unlocked=Math.max(1,data.unlocked||1);
let running=false,frame=0,speed=6,distance=0,bones=0,lives=3,beni,things=[],raf,ducking=false,runLevel=1,difficulty='normal';
const modes={easy:{start:7.5,max:14,ramp:210,hearts:4,spawn:1.15},normal:{start:9,max:17,ramp:145,hearts:3,spawn:1},hard:{start:11,max:21,ramp:100,hearts:2,spawn:.82}};
const levels=[
  {goal:220,name:'Sunny Park',sky:'#a9e7ff',ground:'#b5ea8d',far:'#91bd75',accent:'#fff4a8'},
  {goal:300,name:'Candy Sunset',sky:'#ffc2cf',ground:'#e8a6cc',far:'#cb79ac',accent:'#fff0b8'},
  {goal:380,name:'Magic Forest',sky:'#9edbc3',ground:'#75ae78',far:'#477d5d',accent:'#d8f5c4'},
  {goal:460,name:'Moonlit Hills',sky:'#8d91d9',ground:'#7774a8',far:'#55537f',accent:'#f8edb0'},
  {goal:560,name:'Rainbow Challenge',sky:'#c7b5ff',ground:'#8ed8b2',far:'#6aa38a',accent:'#ffd1e6'}
];
const shop=[{id:'nooutfit',icon:'✕',name:'No Outfit',price:0,type:'outfit'},{id:'nohat',icon:'✕',name:'No Hat',price:0,type:'hat'},{id:'bow',icon:'🎀',name:'Pink Bow',price:8,type:'hat'},{id:'crown',icon:'👑',name:'Crown',price:18,type:'hat'},{id:'cap',icon:'🧢',name:'Cool Cap',price:15,type:'hat'},{id:'scarf',icon:'🧣',name:'Scarf',price:12,type:'outfit'},{id:'vest',icon:'🦺',name:'Adventure',price:25,type:'outfit'},{id:'blue',icon:'🩵',name:'Blue Room',price:20,type:'room'},{id:'space',icon:'🚀',name:'Space Room',price:35,type:'room'},{id:'teddy',icon:'🧸',name:'Teddy Decor',price:10,type:'decor'}];
function save(){localStorage.setItem('beniBigDay',JSON.stringify(data));render()}
function render(){ $('#coins').textContent=data.coins;['hunger','clean','happy'].forEach(k=>$('#'+k).style.width=data[k]+'%');const box=$('#shopItems');box.innerHTML='';shop.forEach(item=>{const b=document.createElement('button'),owned=data.owned.includes(item.id);b.className=owned?'owned':'';b.innerHTML=`${item.icon}<br>${item.name}<br><small>${owned?'USE':`🪙 ${item.price}`}</small>`;b.onclick=()=>buy(item);box.append(b)});refreshLevels()}
function refreshLevels(){const s=$('#courseLevel');if(!s)return;const chosen=Math.min(Number(s.value)||data.unlocked,data.unlocked);s.innerHTML='';levels.forEach((l,i)=>{const o=document.createElement('option');o.value=i+1;o.disabled=i+1>data.unlocked;o.textContent=`${i+1}. ${l.name}${o.disabled?' — LOCKED':''}`;s.append(o)});s.value=chosen;showGoal()}
function showGoal(){const n=Number($('#courseLevel')?.value||1),l=levels[n-1];if(l)$('#levelGoal').textContent=`Reach ${l.goal}m to clear ${l.name}.`}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
function buy(i){if(!data.owned.includes(i.id)){if(data.coins<i.price)return toast('Earn more coins on Treat Trail! 🦴');data.coins-=i.price;data.owned.push(i.id);toast(`${i.name} unlocked! ✨`)}use(i);save()}
function use(i){if(i.type==='hat')$('#hat').textContent=i.id==='nohat'?'':i.icon;if(i.type==='outfit')$('#outfit').textContent=i.id==='nooutfit'?'':i.icon;if(i.type==='room')$('#room').className=`room room-${i.id}`;if(i.type==='decor')$('#decorSide').textContent=i.icon;toast(i.id.startsWith('no')?'Back to fluffy Beni! 🤎':`Beni loves the ${i.name}! 💖`)}
document.querySelectorAll('[data-care]').forEach(b=>b.onclick=()=>{const a=b.dataset.care;if(a==='feed'){data.hunger=Math.min(100,data.hunger+24);data.coins=Math.max(0,data.coins-1);toast('Nom nom nom! 😋')}if(a==='wash'){data.clean=100;toast('Fluffy and clean! 🫧')}if(a==='play'){data.happy=Math.min(100,data.happy+20);toast('Zoomies!! 🎾')}if(a==='sleep'){data.hunger=Math.max(15,data.hunger-8);data.happy=Math.min(100,data.happy+10);toast('Sweet dreams, Beni 🌙')}$('#beni').animate([{transform:'scale(1)'},{transform:'scale(1.18) rotate(-5deg)'},{transform:'scale(1)'}],400);save()});
setInterval(()=>{data.hunger=Math.max(10,data.hunger-1);data.clean=Math.max(10,data.clean-.5);data.happy=Math.max(10,data.happy-.4);save()},12000);
function stopRun(){if(running){running=false;cancelAnimationFrame(raf);data.happy=Math.min(100,data.happy+Math.min(20,bones));save()}$('#runOverlay').classList.remove('hidden');$('#runOverlay h2').textContent='Ready, Beni?';showGoal()}
function tab(run){if(!run)stopRun();$('#homeScene').classList.toggle('hidden',run);$('#runScene').classList.toggle('hidden',!run);$('#homeTab').classList.toggle('active',!run);$('#runTab').classList.toggle('active',run)}$('#homeTab').onclick=()=>tab(false);$('#runTab').onclick=()=>tab(true);$('#leaveRun').onclick=()=>tab(false);
function resetRun(){difficulty=$('#difficulty').value;runLevel=Number($('#courseLevel').value);const m=modes[difficulty];frame=0;speed=m.start+(runLevel-1)*1.25;distance=0;bones=0;lives=m.hearts;things=[];ducking=false;beni={x:105,y:330,vy:0,ground:true,jumps:0};updateHud()}
function updateHud(){$('#distance').textContent=Math.floor(distance);$('#runLevel').textContent=runLevel;$('#bones').textContent=bones;const max=modes[difficulty]?.hearts||3;$('#lives').textContent='● '.repeat(lives)+'○ '.repeat(Math.max(0,max-lives))}
function jump(){if(!running||beni.jumps>=2)return;beni.vy=-18;beni.ground=false;beni.jumps++}function duck(on=true){if(running)ducking=on}
function spawnThing(){const r=Math.random();if(r<.58)things.push({type:'cookie',x:930,y:230+Math.random()*75,w:36,h:36,hit:false});else if(r<.82)things.push({type:'cloud',x:930,y:337,w:52,h:43,hit:false});else things.push({type:'cloud',x:930,y:275,w:52,h:43,hit:false})}
function collide(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function drawThing(t){ctx.save();ctx.translate(t.x,t.y);if(t.type==='cookie'){ctx.fillStyle='#c98246';ctx.beginPath();ctx.arc(18,18,17,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#8e542f';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#68402d';[[9,11],[24,9],[13,24],[26,25]].forEach(p=>{ctx.beginPath();ctx.arc(...p,2.5,0,Math.PI*2);ctx.fill()})}else if(t.type==='cloud'){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(13,28,12,0,Math.PI*2);ctx.arc(27,18,17,0,Math.PI*2);ctx.arc(43,28,12,0,Math.PI*2);ctx.fill();ctx.fillRect(12,27,32,13);ctx.strokeStyle='#b9d9e8';ctx.lineWidth=2;ctx.stroke()}else{ctx.strokeStyle='#5f5a51';ctx.lineWidth=5;ctx.lineCap='round';ctx.beginPath();ctx.arc(12,18,14,3.6,5.9);ctx.arc(36,18,14,3.5,5.8);ctx.stroke()}ctx.restore()}
function draw(){const theme=levels[runLevel-1]||levels[0];ctx.clearRect(0,0,900,430);ctx.fillStyle=theme.sky;ctx.fillRect(0,0,900,375);ctx.fillStyle=theme.accent;ctx.beginPath();ctx.arc(760,75,35,0,Math.PI*2);ctx.fill();ctx.fillStyle=theme.far;for(let i=0;i<9;i++){const tx=i*125-(frame*speed*.18)%125;ctx.fillRect(tx+18,314,7,54);ctx.beginPath();ctx.arc(tx+21,310,24,0,Math.PI*2);ctx.fill()}ctx.fillStyle=theme.ground;ctx.fillRect(0,375,900,55);ctx.save();const ph=ducking?48:72,py=ducking?beni.y+4:beni.y-42;ctx.beginPath();ctx.arc(beni.x+34,py+ph/2,ph/2,0,Math.PI*2);ctx.clip();if(beniPhoto.complete)ctx.drawImage(beniPhoto,beni.x,py,68,ph);ctx.restore();things.forEach(drawThing)}
function loop(){if(!running)return;frame++;const m=modes[difficulty],cfg=levels[runLevel-1];distance+=speed/45;const interval=Math.max(24,Math.floor((94-speed*2.7-runLevel*5)*m.spawn));if(frame%interval===0){spawnThing();const comboChance=Math.max(0,(runLevel-1)*.09);if(Math.random()<comboChance)setTimeout(()=>running&&spawnThing(),230);if(runLevel===5&&Math.random()<.18)setTimeout(()=>running&&spawnThing(),440)}speed=Math.min(m.max+runLevel*1.8,m.start+(runLevel-1)*1.25+distance/(m.ramp-runLevel*10));beni.vy+=1.35;beni.y+=beni.vy;if(beni.y>=330){beni.y=330;beni.vy=0;beni.ground=true;beni.jumps=0}const box={x:beni.x+8,y:beni.y+(ducking?15:-35),w:52,h:ducking?35:62};things.forEach(t=>{t.x-=speed;if(!t.hit&&collide(box,t)){t.hit=true;if(t.type==='cookie'){bones++;data.coins++;toast('+1 coin! Dog cookie! 🍪')}else{lives--;toast(t.type==='cloud'?'Don’t eat the cloud! ☁️':'Ouch! Jump or duck! 💥');if(navigator.vibrate)navigator.vibrate(100)}updateHud()}});things=things.filter(t=>t.x>-70&&!t.hit);draw();if(lives<=0)return endRun(false);if(distance>=cfg.goal)return endRun(true);raf=requestAnimationFrame(loop)}
function startRun(){resetRun();running=true;$('#runOverlay').classList.add('hidden');loop()}function endRun(cleared=false){running=false;cancelAnimationFrame(raf);data.happy=Math.min(100,data.happy+Math.min(20,bones));$('#runOverlay').classList.remove('hidden');if(cleared){const final=runLevel===levels.length;if(!final)data.unlocked=Math.max(data.unlocked,runLevel+1);$('#runOverlay h2').textContent=final?'All levels cleared!':'Level cleared!';$('#levelGoal').textContent=final?'You completed the Beni Challenge.':`Level ${runLevel+1} is now unlocked.`;$('#startRun').textContent=final?'Play again':'Next level';save();refreshLevels();if(!final)$('#courseLevel').value=runLevel+1}else{$('#runOverlay h2').textContent='Try again';$('#levelGoal').textContent=`You reached ${Math.floor(distance)}m of ${levels[runLevel-1].goal}m.`;$('#startRun').textContent='Retry level'}save()}
$('#courseLevel').onchange=showGoal;$('#startRun').onclick=startRun;$('#jump').onpointerdown=jump;$('#duck').onpointerdown=()=>duck(true);$('#duck').onpointerup=()=>duck(false);addEventListener('keydown',e=>{if([' ','ArrowUp','ArrowDown'].includes(e.key))e.preventDefault();if(e.key===' '||e.key==='ArrowUp')jump();if(e.key==='ArrowDown')duck(true)});addEventListener('keyup',e=>{if(e.key==='ArrowDown')duck(false)});render();resetRun();draw();
